name: build

on:
  push:
    branches: [ "main" ]

jobs:
  run-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: echo MNEMONIC="" > .env
      working-directory: ./code

    - run: make install
      working-directory: ./code

    - run: make build
      working-directory: ./code
      
    - run: make test
      working-directory: ./code