name: build

on:
  push:
    branches: [ "master" ]

jobs:
  run-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo MNEMONIC="" > .env
    - run: make install
    - run: make build
    - run: make test